CREATE TYPE "ClientStatus" AS ENUM ('ACTIVE', 'INACTIVE');

ALTER TYPE "ActivityType" ADD VALUE 'CLIENT_CREATED';
ALTER TYPE "ActivityType" ADD VALUE 'CLIENT_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE 'CLIENT_STATUS_CHANGED';

ALTER TABLE "Client"
    ALTER COLUMN "leadId" DROP NOT NULL,
    ADD COLUMN "notes" TEXT,
    ADD COLUMN "status" "ClientStatus" NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;