ALTER TYPE "LeadStatus" ADD VALUE 'PROPOSAL_SENT';

ALTER TABLE "Lead"
ADD COLUMN "estimatedValue" DECIMAL(12, 2),
ADD COLUMN "currency" TEXT NOT NULL DEFAULT 'USD',
ADD COLUMN "createdById" TEXT;

ALTER TABLE "Lead" ADD CONSTRAINT "Lead_createdById_fkey"
    FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;